# Settings for Netlify deployment of the frontend

[build]
  base = "frontend/"
  command = "npm run build"
  publish = "dist"

# Handle SPA routing for React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Define environment variables for production
[build.environment]
  NODE_VERSION = "18"

# For local Netlify development environment
[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "frontend/dist"
  autoLaunch = true
